routes:
  /: home
  /about-us/: about
  /services/: services

collections:
  /blog/:
    permalink: '/blog/{slug}/'
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
